### PR TITLE
Get image

### PR DESCRIPTION
**Pull request by shreesh221298**
Combined Sarthak and Shreesh's code

### CODE REVIEW

**Comment by shreesh221298** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sarthakkharia** [comment]
approved

**Comment by sarthakkharia** [comment]
Approved

**Comment by sarthakkharia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by sarthakkharia — APPROVED** [review]
Approved

**Pull request merged**
