### PR TITLE
Add ability to update a warranty #21

### PR DESCRIPTION
**Pull request by GPSingh97**
Ensure that UUID is always server generated when creating new items #11

### CODE REVIEW

**Comment by GPSingh97** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sarthakkharia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by harsimranmaan — DISMISSED** [review]

**Comment by harsimranmaan** [comment]
there are merge conflicts that need to be resolved. Please rebase locally.

**Comment by sarthakkharia** [comment]
This code is already merged in the getImage branch, that's why closing this pull request

**Pull request closed without merging**
